services:
  app:
    build:
      context: .
      target: dev
    container_name: voecrm-dev
    ports:
      - '3001:3000'
      - '51212:51212'
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}

    command: pnpm dev

volumes:
  node_modules_dev:
