services:
  app:
    build:
      context: .
      target: dev
    container_name: voecrm-dev
    ports:
      - '3001:3000'
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules # Evita conflito entre node_modules do host (Windows) e container (Linux)
    env_file:
      - .env
    depends_on:
      - postgres
    # Instala dependÃªncias antes de rodar o dev server para garantir que tudo esteja sincronizado
    command: sh -c "pnpm install && pnpm dev"

  postgres:
    image: postgres:15-alpine
    container_name: voecrm-db-dev
    env_file:
      - .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres_data_dev:
